---
- name: Listen for events on a webhook
  hosts: all

 ## Define our source for events

  sources:
    - ansible.eda.webhook:
        host: 0.0.0.0
        port: 5000

  ## Define the conditions we are looking for

  # rules:
  # - name: Handle Red Hat Insights event
  #   condition: event.payload is defined
  #   actions:
  #     - debug:
  #         msg: "Received event from Insights"
  #     - run_playbook:
  #         name: eda-playbook-insights.yml

  rules:
  - name: Handle Red Hat Insights event
    condition: event.payload is defined
    action:
      run_playbook:
        name: eda-playbook-insights.yml