---
- name: Listen for events on a webhook
  hosts: all

 ## Define our source for events

  sources:
    - ansible.eda.webhook:
        host: 0.0.0.0
        port: 5000

 ## Define the conditions we are looking for

  rules:
    - name: Greet whoever cheers at Ansible!
      condition: event.payload is defined
      action:
        post_event:
          event:
            greeting: "{{ event.payload.message }}"

    - name: Let Ansible print the greeting message
      condition: event.greeting is defined
      action:
        run_playbook:
          name: eda-greeter.yml

    - name: Setup httpd container on defined hosts
      condition: event.payload.name == "setup-httpd"
      action:
        set_fact:
          fact:
            target_hosts: "{{ event.payload.target }}"

    - name: Run playbook to setup httpd container
      condition: event.target_hosts is defined
      action:
        run_playbook:
          name: eda-playbook-httpd-container.yml