---
- name: Greeting playbook for webhook events
  hosts: localhost
  tasks:
    - name: Debug message
      ansible.builtin.debug:
        msg:
          - "Hostname: {{ event.payload.context.hostname }}"
          - "Version: {{ event.payload.context.rhel_version }}"
          - "Display Name: {{ event.payload.context.display_name }}"