---
- name: Display Insights event and notify on Telegram
  hosts: localhost
  tasks:
    - name: Set Telegram notification
      ansible.builtin.set_fact:
        telegram_msg: |
          "Event type: {{ event.payload.event_type }}"

    - name: Send notify to Telegram
      community.general.telegram:
        token: '{{ telegram_token }}'
        api_args:
          chat_id: '{{ telegram_chat_id }}'
          parse_mode: "markdown"
          text: "{{ telegram_msg }}"
          disable_web_page_preview: true
          disable_notification: false

    - name: Debug message
      ansible.builtin.debug:
        msg:
          - "Event type: {{ event.payload.event_type }}"
