---
- name: Listen for events on multiple sources (Kafka, Webhook, AlertManager)
  hosts: all

  sources:
    - ansible.eda.kafka:
        host: kafka
        port: 9092
        topic: eda-topic

    - ansible.eda.webhook:
        host: 0.0.0.0
        port: 5000

    - name: Enable AlertManager listener
      ansible.eda.alertmanager:
        host: 0.0.0.0
        port: 5001

  rules:
    - name: Run playbook to greet our Kafka peers
      condition: event.body.name == "greeting"
      action:
        run_playbook:
          name: eda-playbook-kafka.yml

    - name: Run playbook to greet our webhook callers
      condition: event.payload.name == "greeting"
      action:
        run_playbook:
          name: eda-playbook-webhook.yml

    - name: Run playbook to setup httpd container
      condition: event.payload.name == "setup-httpd"
      action:
        run_playbook:
          name: eda-playbook-httpd-container.yml

    - name: Let Ansible print information about the alert
      condition: event.payload.status == "firing" or event.payload.status == "resolved"
      action:
        run_playbook:
          name: eda-playbook-alertmanager.yml

    - name: Run playbook to greet our Insights peer
      condition: event.payload.account_id is defined
      action:
        run_playbook:
          name: eda-playbook-insights.yml
