---
- name: Triggering playbook for insights events
  hosts: localhost
  tasks:
    - name: Debug message
      ansible.builtin.debug:
        msg:
          - "Event type: {{ ansible_eda.event.payload.event_type }}"
