---
- name: Listen for events on multiple sources (Kafka, Webhook, AlertManager)
  hosts: all

  sources:
    - ansible.eda.kafka:
        host: 127.0.0.1
        port: 9092
        topic: eda-topic

    - name: listen for alerts
      ansible.eda.alertmanager:
        host: 0.0.0.0
        port: 5001

    - ansible.eda.webhook:
        host: 0.0.0.0
        port: 5000

  rules:
# Rules to greet a user
    - name: Greet whoever cheers at Ansible from a Kafka topic!
      condition: event.name == "greeting"
      action:
        set_fact:
          fact:
            greeting: "{{ event.message }}"

    - name: Greet whoever cheers at Ansible!
      condition: event.payload is defined
      action:
        post_event:
          event:
            greeting: "{{ event.payload.message }}"

    - name: Run playbook to greet our customer
      condition: event.greeting is defined
      action:
        run_playbook:
          name: eda-playbook-kafka.yml

    - name: Setup httpd container on defined hosts
      condition: event.payload.name == "setup-httpd"
      action:
        set_fact:
          fact:
            target_hosts: "{{ event.payload.target }}"

    - name: Run playbook to setup httpd container
      condition: event.target_hosts is defined
      action:
        run_playbook:
          name: eda-playbook-httpd-container.yml

    - name: Let Ansible print information about the alert
      condition: event.alert.status == "firing" or event.alert.status == "resolved"
      action:
        run_playbook:
          name: eda-playbook-alertmanager.yml

    - name: Debug Hello event
      condition: event.alert is defined
      action:
        debug:

