---
- name: Listen for events on a Kafka topic
  hosts: all

  sources:
    - ansible.eda.kafka:
        host: 127.0.0.1
        port: 9092
        topic: eda-topic

  rules:

# Rules to greet a user
    - name: Greet whoever cheers at Ansible from a Kafka topic!
      condition: event.name == "greeting"
      action:
        set_fact:
          fact:
            greeting: "{{ event.message }}"

    - name: Run playbook to greet our customer
      condition: event.greeting is defined
      action:
        run_playbook:
          name: eda-playbook-kafka.yml
