---
- name: Listen for events from AlertManager
  hosts: localhost

  sources:
    - name: listen for alerts
      ansible.eda.alertmanager:
        host: 0.0.0.0
        port: 5001

  rules:
    - name: Run playbook to greet our Kafka peers
      condition: event.payload.status == "firing" or event.payload.status == "resolved"
      actions:
        - run_job_template:
            name: eda-alertmanager
            organization: Default
            job_args:
              extra_vars:
                alerts: "{{ event.payload.alerts }}"
                alertStatus: "{{ event.payload.status }}"