---
- name: Listen for events on a webhook
  hosts: localhost
  sources:
    - redhatinsights.eda.insights:
        host: 0.0.0.0
        port: 5002
        token: redhatinsightstoken

  rules:
    - name: Detect and remediater recommendation event from Insights
      condition: event.payload.event_type == "new-recommendation" and event.payload.events[0].payload.rule_id == "hardening_ssh_root_login|OPENSSH_HARDENING_ROOT_LOGIN_2"
      actions:
        - debug:
        - run_job_template:
            name: "[EDA] Insights remediate SSH root login"
            organization: Default
