---
- name: EDA | Insights | Listen for events on a webhook
  hosts: localhost
  sources:
    - redhatinsights.eda.insights:
        host: 0.0.0.0
        port: 5002
        token: redhatinsightstoken

  rules:
    - name: EDA | Insights | Remediate Malware with Ansible
      condition: event.payload is defined and event.payload.event_type == 'detected-malware'
      actions:
        - debug:
        - run_job_template:
            name: "[EDA] Insights Malware playbook"
            organization: Demo Org
            job_args:
              extra_vars:
                insights_mal_type: "{{ event.payload.event_type }}"
                insights_mal_account_id: "{{ event.payload.account_id }}"
                insights_mal_hostname: "{{ event.payload.host_name }}"
                insights_mal_rules: "{{ event.payload.context.matched_rules }}"
                insights_mal_date: "{{ event.payload.context.matched_at }}"

    - name: EDA | Insights | Remediate Red Hat Insights Advisory with Ansible
      condition: event.payload is defined and event.payload.event_type == 'new-advisory'
      actions:
        - debug:
        - run_job_template:
            name: "[EDA] Insights Advisory playbook"
            organization: Demo Org
            job_args:
              extra_vars:
                insights_adv_type: "{{ event.payload.event_type }}"
                insights_adv_data: "{{ event.payload.events }}"
                insights_adv_host_data: "{{ event.payload.context }}"
                insights_adv_target_host: "{{ event.payload.context.display_name }}"
