---
- name: Listen for events on a webhook
  hosts: localhost


 ## Define our source for events

  sources:
    - ansible.eda.webhook:
        host: 0.0.0.0
        port: 5000

  rules:
  - name: Handle Red Hat Insights event with Ansible
    condition: event.payload is defined
    action:
      run_playbook:
        name: eda-playbook-insights.yml
