---
- name: Listen for events from AlertManager
  hosts: localhost

  sources:
    - name: listen for alerts
      ansible.eda.alertmanager:
        host: 0.0.0.0
        port: 5001

  rules:
    - name: Run playbook to greet our Kafka peers
      condition: event.alert.status == "firing" or event.alert.status == "resolved"
      actions:
        - run_job_template:
            name: eda-alertmanager
            organization: Default
            job_args:
              extra_vars:
                alertName: "{{ event.alert.label.alertName }}"
                alertMessage: "{{ event.alert.label.alertMessage }}"
                alertTargetHosts: "{{ event.alert.label.alertTargetHosts }}"
                alertStatus: "{{ event.alert.label.alertStatus }}"
