---
- name: Listen for events on a webhook
  hosts: localhost
  sources:
    - redhatinsights.eda.insights:
        host: 0.0.0.0
        port: 5002
        token: redhatinsightstoken

  rules:
    - name: Handle Red Hat Insights event with Ansible
      condition: event.payload is defined
      actions:
        - debug:
        - run_job_template:
            name: "[EDA] Insights playbook"
            organization: Default
            job_args:
              extra_vars:
                insights_event_type: "{{ event.payload.event_type }}"
