---
- name: Listen for events on a webhook
  hosts: localhost
  sources:
    - redhatinsights.eda.insights:
        host: 0.0.0.0
        port: 5002
        token: redhatinsightstoken

  rules:
    - name: Handle Red Hat Insights event with Ansible
      condition: event.payload is defined
      actions:
        - debug:
        - run_job_template:
            name: eda-insights
            organization: Default
