---
- name: Listen for events on a Kafka topic
  hosts: localhost

  sources:
    - ansible.eda.kafka:
        host: 192.168.230.1
        port: 9092
        topic: eda-topic

  rules:
    - name: Run playbook to greet our Kafka peers
      condition: event.name == "greeting"
      actions:
        - set_fact:
            fact:
              kafkagreeting: "{{ event.message }}"

        - run_job_template:
            name: eda-kafka
            organization: Default
            job_args:
              extra_vars:
                kafkagreeting: "Hello from a Kafka event triggering automation!!!"
