
plugin: azure.azcollection.azure_rm

#auth_source: cli

plain_host_names: true

# fetches VMs from an explicit list of resource groups instead of default all (- '*')
#include_vm_resource_groups:
#- openenv-xz5hv
#- "{{ lookup('env','AZURE_RESOURCE_GROUP') }}"
