---
- name: EDA | Insights | Show Advisory
  hosts: "localhost"

  tasks:        
  - name: Create an SNOW ticket for Malware resolution
    servicenow.itsm.incident:
      instance:
        host: "{{ snow_url }}"
        username: "{{ snow_username }}"
        password: "{{ snow_password }}"
      caller: "admin"
      state: new
      short_description: "Alert {{ item.payload.matched_rules }} detected on host {{ item.payload.host_name }}"
      description: |
        The following alert triggered on {{ item.payload.host_name }}:
        "Malware {{ item.payload.matched_rules }} detected at {{ item.payload.matched_at }} in {{ item.payload.host_name }} 
        Red Hat Insights account {{ item.payload.account_id }}"
    register: _incident
    loop: "{{ insights_mal_data }}"

  - name: Print out SNOW created incident details
    ansible.builtin.debug:
      var: _incident.results[0]

  - name: Retrieve incident number
    ansible.builtin.set_fact:
      incident_number: "{{ _incident.results[0].record.number }}"

  - name: Print out SNOW created incident number
    ansible.builtin.debug:
      msg: "Incident number {{ incident_number }} created."

  - name: Notificar Slack
    community.general.slack:
      token: T04RP428ZBQ/B04RW4Z11DL/Xow5ljlHZliYA2uSgjVAeLwR
      msg: 'Incident number {{ incident_number }} created.'
      channel: '#insights'
        
  - name: Notificar Telegram
    community.general.telegram:
      token: '1024279922:AAHSx-S_PC0vkjdG1-CqR5RxSIdma1sbZTM'
      api_args:
        chat_id: 11394314
        parse_mode: "html"
        text: "Incident number {{ incident_number }} created."