---
- name: Greeting playbook for webhook events
  hosts: localhost
  tasks:
    - name: Debug message
      ansible.builtin.debug:
        msg:
          - "Event type: {{ event.payload.event_type }}"
