---
- name: EDA | Insights | Show Advisory
  hosts: "{{ insights_adv_target_host }}"
  vars:
    insights_api_url: "https://console.redhat.com/api"
    insights_auth_user: "{{ rhsm_username }}"
    insights_auth_password: "{{ rhsm_password  }}"
    hosts_with_adv: []

  tasks:

    - name: Create a list for each host with advisories
      ansible.builtin.set_fact:
        hosts_with_adv: "{{ hosts_with_adv + [{ 'hostname' : insights_adv_host_data.display_name, 
                                        'insights_id' : insights_adv_host_data.inventory_id,
                                        'advisory_id' : item.payload.advisory_id,
                                        'advisory_name' : item.payload.advisory_name,
                                        'advisory_type' : item.payload.advisory_type }] }}"
      loop: "{{ insights_adv_data }}"

    - name: Debug message
      ansible.builtin.debug:
        msg:
          - "hostname: {{ item.hostname }}"
          - "insights_id: {{ item.insights_id }}"
          - "advisory_id: {{ item.advisory_id }}"
          - "advisory_name: {{ item.advisory_name }}"
          - "advisory_type:  {{ item.advisory_type }}"
      loop: "{{ hosts_with_adv }}"

    - name: Get Insights Tags
      #no_log: true
      uri:
        url: "{{ insights_api_url }}/patch/v3/advisories/{{ item.advisory_name }}"
        method: GET
        return_content: yes
        user: "{{ insights_auth_user }}"
        password: "{{ insights_auth_password }}"
        force_basic_auth: yes
        status_code: 200
      register: insights_cves
      loop: "{{ hosts_with_adv }}"

    - name: Create a list for each host with CVEs
      ansible.builtin.set_fact:
        hosts_with_cve: "{{ hosts_with_cve + [{ 'hostname' : insights_adv_host_data.display_name, 
                                        'insights_id' : insights_adv_host_data.inventory_id,
                                        'advisory_id' : item.json.data.id,
                                        'cves' : item.json.data.attributes.cves, 
                                        'advisory_type_name' : item.json.data.attributes.advisory_type_name,
                                        'severity' : item.json.data.attributes.severity,
                                        'description' : item.json.data.attributes.description }] }}"
      loop: "{{ insights_cves.results }}"

    - name: Print out the list of CVEs for host "{{ insights_adv_target_host }}"
      ansible.builtin.debug:
        var: item
      loop: "{{ hosts_with_cve }}"
