---
- name: EDA | Insights | Show Advisory
  hosts: "{{ insights_adv_target_host }}"
  vars:
    insights_api_url: "https://console.redhat.com/api"
    insights_auth_user: "{{ rhsm_username }}"
    insights_auth_password: "{{ rhsm_password  }}"

  tasks:        
    - name: Create a list for each host with advisories