---
- name: EDA | Insights | Show Advisory
  hosts: "localhost"

  tasks:        
  - name: Create an SNOW ticket for Malware resolution
    servicenow.itsm.incident:
      instance:
        host: "{{ snow_url }}"
        username: "{{ snow_username }}"
        password: "{{ snow_password }}"
      caller: "admin"
      state: new
      short_description: "Alert {{ insights_mal_rules }} detected on host {{ insights_mal_hostname }}"
      description: |
        The following alert triggered on {{ insights_mal_hostname }}:
        "Malware {{ insights_mal_rules }} detected at {{ insights_mal_date }} in {{ insights_mal_hostname }} 
        Red Hat Insights account {{ insights_mal_account_id }}"
    register: _incident

  - name: Print out SNOW created incident details
    ansible.builtin.debug:
      var: _incident.results[0]

  - name: Retrieve incident number
    ansible.builtin.set_fact:
      incident_number: "{{ _incident.results[0].record.number }}"

  - name: Print out SNOW created incident number
    ansible.builtin.debug:
      msg: "Incident number {{ incident_number }} created."

  - name: Notificar Slack
    community.general.slack:
      token: T04RP428ZBQ/B04RW4Z11DL/Xow5ljlHZliYA2uSgjVAeLwR
      msg: 'Incident number {{ incident_number }} created.'
      channel: '#insights'
        
  - name: Notificar Telegram
    community.general.telegram:
      token: '1024279922:AAHSx-S_PC0vkjdG1-CqR5RxSIdma1sbZTM'
      api_args:
        chat_id: 11394314
        parse_mode: "html"
        text: "Incident number {{ incident_number }} created."