---
- name: Playbook reacting to AlertManager Event
  hosts: localhost
  tasks:
    - name: Handle new firing alert
      when: alertStatus == "firing"
      block:
        - name: Debug message
          ansible.builtin.debug:
            msg: "The event {{ item.labels.alertName }} - {{ item.labels.alertMessage }} just triggered on {{ item.labels.alertTargetHosts }} to greet Ansible Event Driven! }}"
          loop: "{{ alerts }}"

        - name: Remediating issue to resolve the alert
          ansible.builtin.debug:
            msg: Trying to solve {{ item.labels.alertName }}
          loop: "{{ alerts }}"
    - name: Notify resolution
      ansible.builtin.debug:
        msg: "The event {{ item.labels.alertName }} was just resolved by Ansible Event Driven!"
      loop: "{{ alerts }}"
      when: alertStatus == "resolved"
