---
- name: Playbook reacting to AlertManager Event
  hosts: localhost
  tasks:
    - name: Handle new firing alert
      when: alertStatus == "firing"
      block:
        - name: Debug message
          ansible.builtin.debug:
            msg: "The event {{ alertName }} - {{ alertMessage }} just triggered on {{ alertTargetHosts }} to greet Ansible Event Driven! }}"

        - name: Remediating issue to resolve the alert
          ansible.builtin.debug:
            msg: Trying to solve {{ alertName }}

    - name: Notify resolution
      ansible.builtin.debug:
        msg: "The event {{ alertName }} was just resolved by Ansible Event Driven!"
      when: alertStatus == "resolved"
