---
- name: Playbook reacting to AlertManager Event with ITSM ticket
  hosts: localhost
  vars:
    snow_instance: https://dev175196.service-now.com/
    snow_username: admin
    snow_password: "2j+-6hjqNCXC"
  tasks:
    - name: Handle new firing alert
      when: alertStatus == "firing"
      block:
        - name: Debug message
          ansible.builtin.debug:
            msg:
              - "The event {{ item.labels.alertName }} just triggered on {{ item.labels.alertTargetHosts }}"
              - "Alert body is: {{ item.labels.alertMessage }}"
          loop: "{{ alerts }}"

        - name: Open ITSM ticket to report incident
          servicenow.itsm.incident:
            instance:
              host: "{{ snow_instance }}"
              username: "{{ snow_username }}"
              password: "{{ snow_password }}"
            state: new
            short_description: "Alert {{ item.labels.alertName }} on host {{ item.item.labels.alertTargetHosts }}"
            description: |
              The following alert triggered on {{ item.item.labels.alertTargetHosts }}:
              "{{ item.labels.alertMessage }}"
          loop: "{{ ansible_eda.event.payload.alerts }}"

        - name: Remediating issue to resolve the alert
          ansible.builtin.debug:
            msg: Trying to solve {{ item.labels.alertName }}
          loop: "{{ alerts }}"

    - name: Notify resolution
      ansible.builtin.debug:
        msg: "The event {{ item.labels.alertName }} was just resolved by Ansible Event Driven!"
      loop: "{{ alerts }}"
      when: alertStatus == "resolved"
